[package]
name = "usbsas-proto"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0"

[build-dependencies]
prost-build = "0.13"

[dependencies]
prost = "0.14"
serde = { version = "1.0", features = ["derive"] }
usbsas-config = { path = "../usbsas-config" }
