#! /bin/sh
set -e

# Create usbsas user, update initramfs and reload udev rules

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
    if [ -z "$(id -u usbsas 2>/dev/null)" ]; then
        echo "adding usbsas user"
        adduser --system  --home /var/lib/usbsas --gecos "usbsas" \
            --disabled-password --quiet usbsas
    fi

    echo "reloading udev rules"
    udevadm control --reload-rules

fi

#DEBHELPER#
