#! /bin/sh
set -e

# Delete usbsas user, update initramfs and reload udev rules

if [ "$1" = remove ]; then
    echo "deleting usbsas user"
    userdel -r -f usbsas

    echo "reloading udev rules"
    udevadm control --reload-rules
fi

#DEBHELPER#
