#! /bin/sh

# Create usbsas user, update initramfs and reload udev rules

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
    set +e
    if [ -z "$(id -u usbsas 2>/dev/null)" ]; then
        set -e
        echo "adding usbsas user"
        adduser --system --group --home /var/lib/usbsas \
            --comment "usbsas" --disabled-password --quiet usbsas
    fi

    echo "reloading udev rules"
    udevadm control --reload-rules

    echo "creating /usbsas_data"
    mkdir -p /usbsas_data
    chown usbsas /usbsas_data

fi

#DEBHELPER#
