#! /bin/bash

# Start hid-dealer if service exists
if systemctl --user list-unit-files | grep -q hid-dealer.service; then
    if systemctl -q --user is-active hid-dealer.service; then
        systemctl --user restart hid-dealer.service
    else
        systemctl --user start hid-dealer.service
    fi
fi

# Set max resolution
monitor=$(xrandr | grep " connected primary" | awk '{print $1}')
mode=$(xrandr | grep -A1 " connected primary" | tail -1 | cut -d ' ' -f4)
xrandr --output "$monitor" --mode "$mode"
window_w=$(echo $mode | cut -dx -f1)
window_h=$(echo $mode | cut -dx -f2)

xsetroot -solid grey95
xdotool mousemove 300 400
xset -dpms
xset s noblank
xset s off
/usr/bin/unclutter -idle 1 -jitter 5 &
exec /usr/bin/usbsas-client /usr/share/usbsas/web --fullscreen -W "$window_w" -H "$window_h"
