#! /bin/bash

# Start hid-dealer if service exists
if systemctl --user list-unit-files | grep -q hid-dealer.service; then
    if systemctl -q --user is-active hid-dealer.service; then
        systemctl --user restart hid-dealer.service
    else
        systemctl --user start hid-dealer.service
    fi
fi

# Set max resolution
monitor=$(xrandr | grep " connected" | awk '{print $1}')
mode=$(xrandr | grep -A1 " connected" | tail -1 | cut -d ' ' -f4)
xrandr --output "$monitor" --mode "$mode"
window_w=$(echo $mode | cut -dx -f1)
window_h=$(echo $mode | cut -dx -f2)

xsetroot -solid black
xdotool mousemove 300 400
xset -dpms
xset s noblank
xset s off
xset s 1800 30
/usr/bin/unclutter -idle 1 -jitter 5 &
exec /usr/bin/usbsas-client --fullscreen -W "${window_w:-1920}" -H "${window_h:-1080}"
