#! /bin/sh
set -e

# Create usbsas user, update initramfs and reload udev rules

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
    if [ -z "$(id -u usbsas 2>/dev/null)" ]; then
        echo "adding usbsas user"
        adduser --system  --home /var/lib/usbsas --gecos "usbsas" \
            --disabled-password --quiet usbsas
    fi

    echo "updating initramfs"
    depmod
    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u 2>/dev/null
    elif [ -x /usr/bin/dracut ]; then
        KVER=$(uname -r)
        kernel-install add $KVER /boot/vmlinuz-$KVER /boot/initrd.img-$KVER
    else
        echo "WARN: couldn't update initramfs !"
    fi

    echo "reloading udev rules"
    udevadm control --reload-rules

fi

#DEBHELPER#
