#! /bin/sh
set -e

if [ "$1" = remove ]; then
    echo "stopping usbsas-server"
    if systemctl -q is-active usbsas-server; then
        systemctl stop usbsas-server
    fi
    if systemctl -q is-enabled usbsas-server; then
        systemctl disable usbsas-server
    fi
fi

#DEBHELPER#
