[package]
name = "usbsas-process"
description = "usbsas-process"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
libc = "0.2"
log = "0.4"
nix = { version = "0.31", features = ["fs", "process"] }
thiserror = "2.0"
usbsas-comm = { path = "../usbsas-comm" }
usbsas-utils = { path = "../usbsas-utils" }
